### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by runlevelsix** [bjrmatos/jsreport-migrate#3]
When running the command `jsreport-migrate` from within a jsreport project, I get this error output:

```
env: node\r: No such file or directory
```

I am using NVM for my node installation, currently set to node v6.3.1.

**Comment by bjrmatos** [comment]
@runlevelsix what OS are you using? windows, linux or OSX?

**Comment by runlevelsix** [comment]
Oops, sorry that I forgot that important piece of info. This is on OS X 10.11.6.

**Comment by bjrmatos** [comment]
@runlevelsix hmmm interesting, i've developed this package in OSX Yosemite, will try with node 6.3.1 and lets see if i can reproduce the issue.

**Comment by runlevelsix** [comment]
I was under the impression that I needed to run this tool for my project, but it turns out that, after talking with @pofider, I do not need to use jsreport-migrate for my jsreport project. Perhaps the issue is related to this fact?
